"""updated trades table, removed equity table, and added account snapshots table

Revision ID: efc889075486
Revises: 53967d03dbe0
Create Date: 2026-01-04 10:57:47.485774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'efc889075486'
down_revision: Union[str, Sequence[str], None] = '53967d03dbe0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cash', sa.Float(), nullable=False),
    sa.Column('equity', sa.Float(), nullable=False),
    sa.Column('buying_power', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ref_trade_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ref_trade_id'], ['trades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_snapshots_as_of'), 'account_snapshots', ['as_of'], unique=False)
    op.create_index(op.f('ix_account_snapshots_id'), 'account_snapshots', ['id'], unique=False)
    op.drop_table('equity')
    op.alter_column('strategies', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.create_index(op.f('ix_strategies_id'), 'strategies', ['id'], unique=False)
    op.add_column('trades', sa.Column('strategy_id', sa.Integer(), nullable=False))
    op.add_column('trades', sa.Column('executed_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('trades', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_trades_id'), 'trades', ['id'], unique=False)
    op.create_index(op.f('ix_trades_strategy_id'), 'trades', ['strategy_id'], unique=False)
    op.create_foreign_key(None, 'trades', 'strategies', ['strategy_id'], ['id'])
    op.drop_column('trades', 'account_balance')
    op.drop_column('trades', 'timestamp')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('trades', sa.Column('account_balance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'trades', type_='foreignkey')
    op.drop_index(op.f('ix_trades_strategy_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_id'), table_name='trades')
    op.drop_column('trades', 'created_at')
    op.drop_column('trades', 'executed_at')
    op.drop_column('trades', 'strategy_id')
    op.drop_index(op.f('ix_strategies_id'), table_name='strategies')
    op.alter_column('strategies', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_table('equity',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('equity_pkey'))
    )
    op.drop_index(op.f('ix_account_snapshots_id'), table_name='account_snapshots')
    op.drop_index(op.f('ix_account_snapshots_as_of'), table_name='account_snapshots')
    op.drop_table('account_snapshots')
    # ### end Alembic commands ###
